Added possibility of setting count to zero (#1050)
enonic/app-users pull request #1051
Opened 2022-05-11 00:37 UTC by reisfmb

2022-05-11 05:31 UTC, rymsha commented on src/main/resources/services/graphql/schema/query.js
> +                var count = env.args.count !== 0 ? (env.args.count || Number.MAX_SAFE_INTEGER) : 0;
Number.MAX_SAFE_INTEGER is still dangerous as default (dispite its name)
0 as default is safer, as it won't allow to similar performance bugs to sneak in

2022-05-11 07:00 UTC, alansemenov requested changes

2022-05-11 07:00 UTC, alansemenov commented on src/main/resources/services/graphql/schema/query.js
>                  return useritems.list(null, query, itemIds, start, count);
This code is duplicate of the one in `userItemsConnection.resolve`, except for nullable `types`. Should be extracted to a separate method which will be called from both places, f.ex.

```
getUserItems: function (args, types) {
  var query = args.query;
  var itemIds = args.itemIds;
  var count = args.count || 0;
  var start = args.start || 0;
  return useritems.list(types, query, itemIds, start, count);
}

userItemsConnection: {
  resolve: function (env) {
     return getUserItems(env.args.types, env.args);
  }
},

types: {
  resolve: function (env) {
     return getUserItems(null, env.args);
  }
},
```

2022-05-14 10:16 UTC, alansemenov approved these changes

2022-05-14 10:16 UTC, merged